Update azure-pipelines.yml for Azure Pipelines

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -20,10 +20,11 @@ steps:
       echo "${GITHUB_SSH_KEY}" > ~/.ssh/id_rsa
       chmod 600 ~/.ssh/id_rsa
       # Eliminar cualquier clave previa de GitHub
-      ssh-keygen -R github.com
+      ssh-keygen -R github.com || true
+      ssh-keygen -R ssh.github.com || true
       ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
       ssh-keyscan -t rsa -p 443 ssh.github.com >> ~/.ssh/known_hosts
-      echo "Host github.com" >> ~/.ssh/config
+      echo "Host github.com" > ~/.ssh/config
       echo "  Hostname github.com" >> ~/.ssh/config
       echo "  User git" >> ~/.ssh/config
       echo "Host ssh.github.com" >> ~/.ssh/config
@@ -37,7 +38,7 @@ steps:
       fi
       echo "Contents of known_hosts:"
       cat ~/.ssh/known_hosts
-      GIT_SSH_COMMAND="ssh -vvv -F ~/.ssh/config" ssh -T git@github.com || { echo "SSH connection to GitHub failed. Aborting."; exit 1; }
+      ssh -T git@github.com || { echo "SSH connection to GitHub failed. Aborting."; exit 1; }
   displayName: 'Set up SSH key for GitHub'
 
 - task: SSH@0
